feat: A lot of deployment / VM improvements
* Update thanos base images
* minio: update to the new auth env vars
* minio: create thanos bucket on container start
* fix filebeat errors by updating the config format
* etcd: downgrade to 3.5 and force the usage of V2 API (removed in 3.6)
* etcd: update the healthcheck command as the previous one was
  deprecated and removed
* hacks for thanos permissions issues with mounted images, so that the
  deployment works again
* vm script: immediately stop the VM if --force is used (saves a lot of time)
* vm script: add a command to show information about the Optscale
  deployment making it easier to troubleshoot issues
* vm script: add a command to deploy local changes to the VM for a given service

diff --git a/optscale-deploy/vm b/optscale-deploy/vm
--- a/optscale-deploy/vm
+++ b/optscale-deploy/vm
@@ -97,6 +97,22 @@ function vm_start {
 function vm_stop {
     # shellcheck disable=2068
     vagrant halt $vm_name $@
+
+    # if the --force flag is used, we can kill the vm process immediately as vagrant / qemu takes a while to stop the VM
+    # even when --force is used
+    if [[ "$@" == *"--force"* ]]; then
+        vm_process_info=$(ps -eo pid,command \
+                        | grep "qemu-system-.*$vm_name" \
+                        | grep -v "grep" \
+                        || echo "")
+
+        
+        vm_qemu_pid=$(echo "$vm_process_info" | cut -d ' ' -f '1' || echo "")
+
+        if [[ -n "$vm_qemu_pid" ]]; then
+            kill "$vm_qemu_pid"
+        fi
+    fi
     
     # After the vagrant halt often the VM is still running in the background
     # It should stop automatically eventually but if we don't wait for it and run another
@@ -120,10 +136,12 @@ function vm_ssh {
     # In these cases we can just set it to 'xterm-256color' which is widely recognised and provides similar,
     # albeit more limitted, color support
 
+    cmd_to_run="${1:-/bin/bash}"
+
     if [[ "$TERM" == "xterm-kitty" ]]; then
-        TERM="xterm-256color" vagrant ssh $vm_name -c "/bin/bash"
+        TERM="xterm-256color" vagrant ssh $vm_name -c "$cmd_to_run"
     else
-        vagrant vagrant ssh $vm_name -c "/bin/bash"
+        vagrant vagrant ssh $vm_name -c "$cmd_to_run"
     fi
 }
 
@@ -175,6 +193,45 @@ function vm_run_ansible_role {
         $@
 }
 
+function vm_show_optscale_info {
+    cluster_secret=$(vm_ssh "kubectl get secret cluster-secret -o jsonpath='{.data.cluster_secret}' | base64 --decode")
+    cluster_ip_addr=$(vm_ssh "kubectl get services --no-headers --field-selector metadata.name=ngingress-nginx-ingress-controller -o custom-columns=ClusterIP:.spec.clusterIP")
+    forwarded_https_port=$(cat "$SCRIPT_DIR/Vagrantfile" \
+        | grep 'define_vm' -A 10 \
+        | grep "name.*$vm_name" -A 10 \
+        | grep "https: \(\d\+\)" -m 1 -o \
+        | awk '{print $2}'
+    )
+      
+    frontend_url="https://localhost:$forwarded_https_port/"
+    status_code=$(curl --insecure -L -I -X GET "$frontend_url" -sw '%{http_code}\n' -o /dev/null)
+    echo "Frontend URL: $frontend_url [HTTP Status: $status_code]"
+    echo "Cluster IP Address: $cluster_ip_addr"
+    echo "Cluster Secret: $cluster_secret"
+
+    # ref: https://blog.cubieserver.de/2021/list-all-failed-pods-in-a-namespace-with-kubectl/
+    failing_pods=$(vm_ssh "kubectl get pods -o custom-columns="POD:metadata.name,STATE:status.containerStatuses[*].state.waiting.reason" | grep -v '<none>'")
+    echo
+    echo "Failing Pods"
+    echo "-----------"
+    echo
+    echo "$failing_pods"
+}
+
+function vm_deploy_service {
+    local service_name="$1"
+
+    if [[ -z "$service_name" ]]; then
+        echo "Error: Service name is required."
+        exit 1
+    fi
+
+    vagrant rsync "$vm_name"
+    vm_ssh "cd optscale && ./build.sh --use-nerdctl $service_name local"
+    vm_ssh "cd optscale/optscale-deploy && .venv/bin/python runkube.py --no-pull -o 'overlay/user_template.yml' -- optscale local"
+}
+
+
 if [[ "$command" == "info" ]]; then
     vm_info
 elif [[ "$command" == "start" || "$command" == "up" ]]; then
@@ -191,13 +248,17 @@ elif [[ "$command" == "reset" ]]; then
     vm_destroy
     vm_start
 elif [[ "$command" == "ssh" ]]; then
-    vm_ssh
+    vm_ssh $@
 elif [[ "$command" == "playbook" ]]; then
     # shellcheck disable=2068
     vm_run_ansible_playbook $@
 elif [[ "$command" == "role" ]]; then
     # shellcheck disable=2068
     vm_run_ansible_role $@
+elif [[ "$command" == "optscale-info" ]]; then
+    vm_show_optscale_info
+elif [[ "$command" == "deploy-service" ]]; then
+    vm_deploy_service $@
 else
     echo "Error: Invalid command: $command"
     echo "$usage_str"
